version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
