version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/prueba
      QUARKUS_DATASOURCE_USERNAME: prueba
      QUARKUS_DATASOURCE_PASSWORD: 12345678

volumes:
  pgdata:
